import {
    AppstoreOutlined,
    BarChartOutlined,
    CloudOutlined,
    ShopOutlined,
    TeamOutlined,
    UploadOutlined,
    UserOutlined,
    VideoCameraOutlined,
} from '@ant-design/icons';

import Head from 'next/head';
import React from 'react';
import { Layout, Menu, theme } from 'antd';
import FooterLayout from '@/components/Layout/Footer';
import HeaderLayout from '@/components/Layout/Header';
import Navigation from '@/components/Layout/Navigation';
const { Header, Content, Footer, Sider } = Layout;

export default function LayoutApp({ children }) {
    const {
        token: { colorBgContainer },
    } = theme.useToken();

    return (
        <React.Fragment>
            <Head>
                <title>DATN - CMS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <React.Fragment>
                <Layout hasSider>
                    <Navigation />
                    <Layout
                        className="site-layout min-h-screen h-auto"
                        style={{
                            marginLeft: 200,
                        }}
                    >
                        <HeaderLayout />
                        <Content className="my-4 ml-8">{children}</Content>
                        <FooterLayout />
                    </Layout>
                </Layout>
            </React.Fragment>
        </React.Fragment>
    );
}
