import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/globals.css';
import Head from 'next/head';
import React from 'react';
import "tailwindcss/tailwind.css";
import { SessionProvider } from "next-auth/react"

export default function App({ Component, pageProps:{ session, ...pageProps } }) {
    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SessionProvider session={session}>
                <Header />
                <Component {...pageProps} />
                <Footer />
            </SessionProvider>
        </React.Fragment>
    );
}
