import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/globals.css';
import Head from 'next/head';
import React from 'react';
import "tailwindcss/tailwind.css";
import { wrapper } from '@/redux/store';

const App = ({ Component, pageProps: { session, ...pageProps } }) => {
    return (
        <React.Fragment>
            <Head>
                <title>BOOKING.COM</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Header />
                <Component {...pageProps} />
                <Footer />
            </>
        </React.Fragment>
    );
}

export default wrapper.withRedux(App);