import Footer from '@/components/Layout/Footer';
import Header from '@/components/Layout/Header';
import '@/styles/globals.css';
import Head from 'next/head';
import React from 'react';
import 'tailwindcss/tailwind.css';
import { wrapper } from '@/redux/store';
import { useNProgress } from '@/hooks/useNProgress';

const App = ({ Component, pageProps: { ...pageProps } }) => {
    useNProgress();
    return (
        <React.Fragment>
            <Head>
                <title>Datphong.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <Header />
                <Component {...pageProps} />
                <Footer />
            </>
        </React.Fragment>
    );
};

export default wrapper.withRedux(App);
